library(foreign)
women_work<-read.dta("data-raw/women_work.dta")
arch_1<-read.dta("data-raw/arch_1.dta")
asclogit<-read.dta("data-raw/asclogit.dta")
auto<-read.dta("data-raw/auto.dta")
barium<-read.dta("data-raw/BARIUM.dta")
ceosal<-read.dta("data-raw/CEOSAL1.dta")
college<-read.dta("data-raw/college.dta")
counting<-read.dta("data-raw/counting.dta")
gpa<-read.dta("data-raw/GPA1.dta")
heckit<-read.dta("data-raw/heckit.dta")
phillipse<-read.dta("data-raw/phillips.dta")
#
usethis::use_data(women_work,overwrite = TRUE)
usethis::use_data(arch_1,overwrite = TRUE)
usethis::use_data(asclogit,overwrite = TRUE)
usethis::use_data(auto,overwrite = TRUE)
usethis::use_data(barium,overwrite = TRUE)
usethis::use_data(ceosal,overwrite=TRUE)
usethis::use_data(college,overwrite = TRUE)
usethis::use_data(counting,overwrite = TRUE)
usethis::use_data(gpa,overwrite = TRUE)
usethis::use_data(heckit,overwrite = TRUE)
usethis::use_data(phillipse,overwrite = TRUE)
